//! Prepares the carousel photographs at build time, replacing what `astro:assets` and
//! `exifreader` did in the Astro original.
//!
//! For every `assets/*.jpg` this:
//!
//! - reads the caption from the IPTC Object Name field embedded by Lightroom
//! - writes resized copies into `public/photos/`, which Trunk copies into `dist/`
//! - emits `$OUT_DIR/photos.rs`, a `PHOTOS` table the app includes
//!
//! Captions have to be extracted here rather than in the app, because the wasm bundle
//! should not carry an image decoder or the 9 MB of originals.

use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use image::codecs::jpeg::JpegEncoder;
use image::imageops::FilterType;

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=assets");
    println!("cargo::rerun-if-changed=build.rs");

    fs::create_dir_all(OUTPUT_DIR)?;

    let mut sources = fs::read_dir("assets")?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "jpg"))
        .collect::<Vec<_>>();

    // Directory order is arbitrary; the carousel needs a stable slide order.
    sources.sort();

    let mut photos = Vec::with_capacity(sources.len());
    for source in &sources {
        photos.push(prepare(source)?);
    }

    let table = photos
        .iter()
        .map(|photo| photo.entry())
        .collect::<Vec<_>>()
        .join("\n");

    let destination = PathBuf::from(std::env::var("OUT_DIR")?).join("photos.rs");
    fs::write(
        destination,
        format!(
            "/// Carousel slides, generated by `build.rs` from `assets/*.jpg`.\n\
             pub const PHOTOS: &[Photo] = &[\n{table}\n];\n"
        ),
    )?;

    Ok(())
}

/// One photograph, with the widths that were written out for it.
struct Photo {
    stem: String,
    caption: String,
}

impl Photo {
    fn entry(&self) -> String {
        let Self { stem, caption } = self;
        let caption = caption.replace('"', "\\\"");

        format!(
            "    Photo {{ small: \"/photos/{stem}-{SMALL}.jpg\", \
             large: \"/photos/{stem}-{LARGE}.jpg\", caption: \"{caption}\" }},"
        )
    }
}

/// Resizes one source image into every target width and reads back its caption.
fn prepare(source: &Path) -> Result<Photo, Box<dyn Error>> {
    let stem = source
        .file_stem()
        .and_then(|stem| stem.to_str())
        .ok_or("photo file name is not valid UTF-8")?
        .to_owned();

    let bytes = fs::read(source)?;
    let caption = caption(&bytes).unwrap_or_default();
    let targets = [SMALL, LARGE].map(|width| (width, output_path(&stem, width)));

    if targets.iter().all(|(_, path)| is_fresh(path, source)) {
        return Ok(Photo { stem, caption });
    }

    let original = image::load_from_memory(&bytes)?;
    for (width, path) in &targets {
        // `resize` fits inside the box given, so round the height up: rounding down loses a
        // pixel of width and makes the srcset `w` descriptor a lie.
        let height = (width * original.height()).div_ceil(original.width().max(1));
        let resized = original.resize(*width, height, FilterType::Lanczos3);

        let mut encoded = Vec::new();
        resized.write_with_encoder(JpegEncoder::new_with_quality(&mut encoded, QUALITY))?;
        fs::write(path, encoded)?;
    }

    Ok(Photo { stem, caption })
}

fn output_path(stem: &str, width: u32) -> PathBuf {
    Path::new(OUTPUT_DIR).join(format!("{stem}-{width}.jpg"))
}

/// Reports whether `output` already exists and is no older than `source`, so that editing
/// a photograph regenerates it but an ordinary rebuild does not.
fn is_fresh(output: &Path, source: &Path) -> bool {
    let modified = |path: &Path| fs::metadata(path).and_then(|meta| meta.modified()).ok();

    match (modified(output), modified(source)) {
        (Some(output), Some(source)) => output >= source,
        _ => false,
    }
}

/// Extracts the IPTC Object Name (record 2, dataset 5) that Lightroom writes as the photo
/// title. It lives in an APP13 "Photoshop 3.0" segment, as a chain of 8BIM resources; the
/// one holding IPTC data has id 0x0404.
///
/// The same string is also present as XMP `dc:title`, but IPTC is a compact binary format
/// and needs no XML parser.
fn caption(bytes: &[u8]) -> Option<String> {
    let start = find(bytes, PHOTOSHOP_MARKER)? + PHOTOSHOP_MARKER.len();
    let iptc = iptc_resource(&bytes[start..])?;

    let mut rest = iptc;
    while rest.len() >= 5 && rest[0] == 0x1c {
        let length = usize::from(u16::from_be_bytes([rest[3], rest[4]]));
        let value = rest.get(5..5 + length)?;

        if rest[1] == 2 && rest[2] == 5 {
            return String::from_utf8(value.to_vec()).ok();
        }

        rest = &rest[5 + length..];
    }

    None
}

/// Walks the 8BIM resource chain and returns the payload of the IPTC resource.
fn iptc_resource(bytes: &[u8]) -> Option<&[u8]> {
    let mut rest = bytes;

    while rest.len() > 12 && &rest[..4] == b"8BIM" {
        let id = u16::from_be_bytes([rest[4], rest[5]]);

        // A Pascal string holds the resource name, padded to an even length.
        let name_length = usize::from(rest[6]);
        let padded = (name_length + 2) & !1;
        let after_name = rest.get(6 + padded..)?;

        let length =
            u32::from_be_bytes([after_name[0], after_name[1], after_name[2], after_name[3]])
                as usize;
        let payload = after_name.get(4..4 + length)?;

        if id == IPTC_RESOURCE_ID {
            return Some(payload);
        }

        // Resource payloads are padded to an even length too.
        rest = after_name.get(4 + length + (length & 1)..)?;
    }

    None
}

fn find(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack
        .windows(needle.len())
        .position(|window| window == needle)
}

const OUTPUT_DIR: &str = "public/photos";
const PHOTOSHOP_MARKER: &[u8] = b"Photoshop 3.0\0";
const IPTC_RESOURCE_ID: u16 = 0x0404;
const SMALL: u32 = 400;
const LARGE: u32 = 800;
const QUALITY: u8 = 70;
