[workspace]
members = ["preview"]
resolver = "3"

[package]
name = "portfolio"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
console_error_panic_hook = "0.1"
leptos = { version = "0.8", features = ["csr"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
